import { Citizenship, IncomeDocType } from "../types/enums";
import type { Scenario } from "../types/scenario";
import type { NeedsListItem } from "../types/results";

function item(category: string, label: string, reason: string, required = true): NeedsListItem {
  return { category, label, required, reason };
}

/**
 * Deterministic broker-facing needs list derived from the scenario's structure.
 * The AI layer may rephrase or annotate this list, but the items themselves are
 * generated by rules so they are consistent and auditable.
 */
export function generateNeedsList(scenario: Scenario): NeedsListItem[] {
  const items: NeedsListItem[] = [];

  // Universal
  items.push(
    item("application", "Completed 1003 Uniform Residential Loan Application (URLA)", "Standard application document every lender requires."),
    item("application", "MISMO 3.4 data file", "Standard electronic loan-data file most lenders require for submission/import."),
    item("identity", "Government-issued photo ID for each borrower", "Identity verification required by all programs."),
    item("credit", "Credit report (tri-merge where available)", "FICO and tradeline review."),
    item("assets", "Two most recent months of statements for the account(s) funding the down payment and closing costs", "Funds-to-close sourcing and seasoning."),
  );

  if (scenario.loanPurpose === "purchase") {
    items.push(item("transaction", "Fully executed purchase contract with all addenda", "Defines price, terms, and timelines."));
  } else {
    items.push(
      item("transaction", "Current mortgage statement(s) for the subject property", "Payoff and housing-history verification."),
      item("transaction", "Evidence of current hazard insurance", "Required for refinance underwriting."),
    );
  }

  switch (scenario.incomeDocType) {
    case IncomeDocType.BankStatement: {
      const months = scenario.bankStatement?.months ?? 12;
      const type = scenario.bankStatement?.personalOrBusiness ?? "business";
      items.push(
        item("income", `${months} months of complete ${type} bank statements (all pages)`, "Deposit analysis for qualifying income."),
        item("income", "Business narrative / description of services", "Supports expense-factor reasonableness."),
      );
      if (type === "business") {
        items.push(item("income", "Evidence of business ownership percentage (operating agreement, K-1, or CPA letter)", "Ownership percentage is applied to deposits."));
      }
      if (scenario.bankStatement?.expenseFactorSource === "cpa" || scenario.bankStatement?.expenseFactorSource === "ea") {
        items.push(item("income", "CPA/EA expense-factor letter", "Documents the expense factor used for qualifying."));
      }
      if (scenario.bankStatement?.hasCashDeposits || scenario.bankStatement?.hasAtmDeposits) {
        items.push(item("income", "Letter of explanation for cash/ATM deposits", "Cash deposits receive program-specific treatment.", true));
      }
      break;
    }
    case IncomeDocType.ProfitAndLoss:
      items.push(
        item("income", "CPA/EA-prepared profit-and-loss statement for the required period", "Primary qualifying income document."),
        item("income", "CPA/EA license verification", "Preparer credential check."),
        item("income", "2 months of business bank statements (program-dependent)", "Deposit support for P&L revenue.", false),
      );
      break;
    case IncomeDocType.Dscr:
      items.push(
        item("income", "Current lease agreement(s) or STR operating history", "Establishes qualifying rent."),
        item("income", "Appraisal with market-rent analysis (Form 1007/1025)", "Market-rent basis for DSCR."),
        item("property", "Evidence of taxes, insurance, HOA dues", "PITIA components of the DSCR denominator."),
      );
      if (scenario.vesting === "llc" || scenario.vesting === "corporation") {
        items.push(item("entity", "Entity documents: articles, operating agreement, EIN letter, certificate of good standing", "Entity vesting requirements."));
      }
      break;
    case IncomeDocType.AssetDepletion:
      items.push(
        item("income", "Most recent statements for all asset accounts used for depletion (typically 2-3 months)", "Asset-depletion income basis."),
        item("income", "Evidence of vesting/ownership for retirement accounts", "Vested balances only are counted."),
      );
      break;
    case IncomeDocType.Income1099:
      items.push(item("income", "Two years of 1099s plus YTD evidence of receipts", "1099 qualifying income basis."));
      break;
    case IncomeDocType.FullDoc:
      items.push(
        item("income", "W-2s for the past two years", "Full-documentation income review — wage-earner history."),
        item("income", "Personal tax returns for the past two years (and business returns, if self-employed)", "Full-documentation income review."),
        item("income", "Most recent one month of pay stubs", "Confirms current income is consistent with tax history."),
      );
      break;
    default:
      break;
  }

  if (scenario.citizenship === Citizenship.ForeignNational) {
    items.push(
      item("residency", "Valid passport from the country of origin", "Identity verification for foreign nationals."),
      item("residency", "Valid visa (where applicable)", "Immigration/eligibility status for foreign nationals."),
      item("residency", "Evidence of funds in a U.S. account or acceptable transfer path", "Funds-to-close sourcing."),
      item(
        "residency",
        "Certified English translation of any bank statements from a foreign (non-U.S.) account",
        "Foreign-language account statements must be translated before they can be used for underwriting.",
        false,
      ),
      item("residency", "Foreign credit reference letters or international credit report (program-dependent)", "Credit depth for borrowers without U.S. credit.", false),
    );
  }
  if (scenario.citizenship === Citizenship.Itin) {
    items.push(
      item("residency", "ITIN card or IRS ITIN assignment letter (both pages)", "ITIN program identity requirement — both pages of the letter/card are required."),
      item("identity", "Second form of identification", "Most ITIN programs require a secondary ID in addition to the primary government-issued photo ID."),
    );
  }
  if (scenario.citizenship === Citizenship.NonPermanentResident) {
    items.push(item("residency", "Valid visa or EAD (work authorization)", "Non-permanent-resident eligibility."));
  }

  const ce = scenario.creditEvents;
  if (ce?.bankruptcyMonthsSinceDischarge != null) {
    items.push(item("credit", "Bankruptcy discharge papers and full schedule", "Seasoning measured from discharge date."));
  }
  if (ce?.foreclosureMonthsSince != null || ce?.shortSaleMonthsSince != null) {
    items.push(item("credit", "Documentation of foreclosure/short-sale completion date", "Seasoning verification."));
  }
  if ((ce?.housingHistoryMonths ?? 12) < 12) {
    items.push(item("credit", "12-month housing-payment history (VOR/VOM or canceled checks)", "Most programs require 12 months of documented housing history.", false));
  }

  return items;
}
