// Batch 5 lender ingestion — 6 more real, publicly-sourced Non-QM lenders
// requested by the user. All placed in Tier 2 by default (no tier was
// specified for these) — disclosed, easy to move later the same way
// prior batches' tiers were reassigned.
//
// "Ardi" (as the user wrote it) is the real company ARDRI (ardri.com) —
// added under its correct real brand name, ARDRI, with the user's
// spelling noted in its notes field.
const TODAY = new Date().toISOString().slice(0, 10);

export const LENDERS = [
  {
    name: "ClearEdge Lending",
    tierLevel: 2,
    notes:
      "Non-QM wholesale lender (ClearEdge Lending LLC). Guideline figures below are from its public Investor Connect (DSCR) product page.",
    program: {
      name: "Investor Connect DSCR",
      incomeDocTypes: ["dscr"],
      loanPurposes: ["purchase", "rate_term_refinance", "cash_out_refinance"],
      occupancies: ["investment"],
      propertyTypes: ["single_family", "condo", "non_warrantable_condo", "2_4_unit"],
      eligibleStates: "ALL",
      citizenshipEligible: ["us_citizen", "permanent_resident"],
      vestingEligible: ["llc", "corporation"],
      minLoanAmount: 100000,
      maxLoanAmount: 2500000,
      minFico: 620,
      minDscr: 0.75,
      baseMaxLtv: 75,
      minReservesMonths: 6,
      interestOnlyAvailable: false,
      prepaymentPenaltyOptions: [],
      guidelineVersionLabel: "Public site — Investor Connect DSCR",
      effectiveDate: TODAY,
      lastVerifiedDate: TODAY,
      sourceCitation: "https://clearedgelending.com/non-qm/investor-loan/",
      notes:
        "Public page states \"Loans up to $2.5Million\", \"Credit Score as low as 620\", \"DSCR down to .75\", 1-4 family and warrantable/non-warrantable condos, close in LLC or Corporation, no TRID waiting periods. The 75% max LTV and 6-month reserves figures come from ClearEdge's public Investor Connect Matrix PDF (loan amounts >$1M max 65% LTV, <=$1M max 70-75% depending on purpose) — 75% used here as the representative purchase-tier ceiling; exact LTV varies by loan amount/purpose per that matrix, verify at quote time.",
    },
  },
  {
    name: "AmWest Funding Corp.",
    tierLevel: 2,
    notes: "AmWest Funding Corp. (NMLS #167441). Guideline figures below are from its public Investor Advantage DSCR matrix PDF.",
    program: {
      name: "Investor Advantage DSCR",
      incomeDocTypes: ["dscr"],
      loanPurposes: ["purchase", "rate_term_refinance", "cash_out_refinance"],
      occupancies: ["investment"],
      propertyTypes: ["single_family", "2_4_unit"],
      eligibleStates: "ALL",
      citizenshipEligible: ["us_citizen", "permanent_resident", "foreign_national"],
      vestingEligible: ["llc", "corporation", "trust"],
      minLoanAmount: 100000,
      maxLoanAmount: 2500000,
      minFico: 620,
      minDscr: 0.85,
      baseMaxLtv: 75,
      minReservesMonths: 0,
      interestOnlyAvailable: true,
      prepaymentPenaltyOptions: [],
      guidelineVersionLabel: "Public PDF — AmWest Investor Advantage Matrix Guidelines",
      effectiveDate: "2023-10-26",
      lastVerifiedDate: TODAY,
      sourceCitation:
        "https://amwestfunding.com/docs/Matrix%20Guideline/AmWest%20Investor%20Advantage%20-%20MATRIX%20GUIDELINES%20-%20October%2026,%202023.pdf",
      notes:
        "Public matrix PDF states, for 1-4 Unit investment properties (Purchase/Rate-Term), max loan $1,500,000 at 75%/70%/60% LTV tiers (660/640/620 FICO respectively) or $2,500,000 at 75%/65% LTV (660/640 FICO). Min Debt Coverage Ratio (DSCR) >= 0.85 (>= 1.00 for LTVs 75.01-80%). Foreign Nationals eligible up to 75% LTV ($1.5M) or 70% LTV ($2.5M). Interest-only option available at reduced max LTV (70% purchase/65% cash-out) with higher minimum FICO (700/720).",
    },
  },
  {
    name: "Hometown Equity Mortgage",
    tierLevel: 2,
    notes:
      "Hometown Equity Mortgage, LLC, dba theLender (NMLS #133519). Guideline figures below are from its public theNONI (DSCR business-purpose loan) pages.",
    program: {
      name: "theNONI DSCR",
      incomeDocTypes: ["dscr"],
      loanPurposes: ["purchase", "rate_term_refinance", "cash_out_refinance"],
      occupancies: ["investment"],
      propertyTypes: ["single_family", "condo", "2_4_unit", "rural"],
      eligibleStates: "ALL",
      citizenshipEligible: ["us_citizen", "permanent_resident", "foreign_national"],
      vestingEligible: ["llc", "corporation", "trust"],
      minLoanAmount: 100000,
      maxLoanAmount: 3500000,
      minFico: 620,
      baseMaxLtv: 80,
      minReservesMonths: 0,
      interestOnlyAvailable: true,
      prepaymentPenaltyOptions: ["none", "3-year step-down", "5-year step-down"],
      guidelineVersionLabel: "Public site — theNONI (Non Owner No Income)",
      effectiveDate: TODAY,
      lastVerifiedDate: TODAY,
      sourceCitation: "https://htem.com/thenoni/ ; https://htem.com/",
      notes:
        "Public homepage states DSCR product has \"No minimum DSCR\", \"As little as 0 months reserves\", \"FICO's as low as 620\", up to 8 units and mixed use OK. Loan amount range (MIN $100,000 / MAX $3,500,000 for the base theNONI product) and the 80% LTV ceiling are drawn from theLender's public wholesale program matrix PDF (a related \"theNONI/theNearNONI/theSuperNONI\" family of products with different LTV ceilings per sub-variant — 80% used here as the representative refinance ceiling stated publicly; confirm the applicable sub-variant and its exact LTV at quote time).",
    },
  },
  {
    name: "Logan Finance Corporation",
    tierLevel: 2,
    notes: "Logan Finance Corporation (Logan Finance Wholesale). Guideline figures below are from its public DSCR Loan product page.",
    program: {
      name: "DSCR Loan (Investor Cash Flow)",
      incomeDocTypes: ["dscr"],
      loanPurposes: ["purchase", "rate_term_refinance", "cash_out_refinance"],
      occupancies: ["investment"],
      propertyTypes: ["single_family", "2_4_unit"],
      eligibleStates: "ALL",
      citizenshipEligible: ["us_citizen", "permanent_resident", "foreign_national"],
      vestingEligible: ["llc", "corporation"],
      minLoanAmount: 100000,
      maxLoanAmount: 2000000,
      minFico: 680,
      minDscr: 1.0,
      baseMaxLtv: 80,
      minReservesMonths: 0,
      interestOnlyAvailable: true,
      prepaymentPenaltyOptions: [],
      guidelineVersionLabel: "Public site — DSCR Loan (Investor Cash Flow)",
      effectiveDate: TODAY,
      lastVerifiedDate: TODAY,
      sourceCitation: "https://loganwholesale.com/dscr-loan/",
      notes:
        "Public page states \"$2 million Loan Amounts\", \"1-4 Units\", \"Low Ratio 0.8:1-1:1 Ratio\", \"DSCR 1:1 – 680 Min Credit\" (a lower \"DSCR Elite 1.20 and up\" tier gets better pricing at the same or better terms), \"Up to 80% LTV\", First Time Investor OK, Foreign National OK, 100% gift funds allowed. Logan also offers a separate 660-min-FICO \"Open Road DSCR\" variant (up to $3M, 80% LTV) — only the base DSCR Loan program's published figures are used in this entry.",
    },
  },
  {
    name: "Cake Mortgage",
    tierLevel: 2,
    notes:
      "Cake Mortgage Corp. — describes itself as \"The Fastest Growing Non-QM Wholesale Lender in the Nation.\" Guideline figures below are primarily from its public DSCR Loan Eligibility Guidelines PDF, with the minimum FICO cross-referenced against a third-party DSCR rate-comparison summary since the official PDF's full matrix table was not captured in this research pass.",
    program: {
      name: "DSCR Loan (1-4 Unit)",
      incomeDocTypes: ["dscr"],
      loanPurposes: ["purchase", "rate_term_refinance", "cash_out_refinance"],
      occupancies: ["investment"],
      propertyTypes: ["single_family", "condo", "2_4_unit"],
      eligibleStates: "ALL",
      citizenshipEligible: ["us_citizen", "permanent_resident"],
      vestingEligible: ["llc", "corporation", "trust"],
      minLoanAmount: 100000,
      maxLoanAmount: 2000000,
      minFico: 640,
      baseMaxLtv: 80,
      minReservesMonths: 0,
      interestOnlyAvailable: false,
      prepaymentPenaltyOptions: [],
      guidelineVersionLabel: "Public PDF — DSCR Loan Eligibility Guidelines",
      effectiveDate: TODAY,
      lastVerifiedDate: TODAY,
      sourceCitation: "https://caketpo.com/wp-content/uploads/2025/01/CAKE-DSCR-FINAL-2.0.pdf",
      notes:
        "Official PDF confirms the program structure: business-purpose DSCR loans for non-owner-occupied investment properties, available to experienced investors, first-time investors, and first-time homebuyers; DSCR = Gross Rental Income / Qualifying Monthly Mortgage Payment (PITIA or ITIA for interest-only). Minimum FICO of 640 and the $2,000,000/80% LTV figures used here are corroborated by a third-party DSCR rate-comparison page (dscrdirect.net) rather than read directly off Cake's own matrix table — this entry should be re-verified against Cake's full published matrix at the next guideline recheck.",
    },
  },
  {
    name: "ARDRI",
    tierLevel: 1,
    notes:
      "Requested by the user as \"Ardi\" — the real company is ARDRI (ardri.com), a Non-QM/business-purpose lender. Added under its correct real brand name. Guideline figures below are from its public DSCR Loan Program page.",
    program: {
      name: "DSCR Loan Program",
      incomeDocTypes: ["dscr"],
      loanPurposes: ["purchase", "rate_term_refinance", "cash_out_refinance"],
      occupancies: ["investment"],
      propertyTypes: ["single_family", "condo", "non_warrantable_condo", "2_4_unit", "pud", "rural"],
      eligibleStates: "ALL",
      citizenshipEligible: ["us_citizen", "permanent_resident", "non_permanent_resident", "itin", "foreign_national"],
      vestingEligible: ["individual", "llc", "corporation", "trust"],
      minLoanAmount: 100000,
      maxLoanAmount: 4000000,
      minFico: 600,
      minDscr: 0.75,
      baseMaxLtv: 80,
      minReservesMonths: 0,
      interestOnlyAvailable: true,
      prepaymentPenaltyOptions: [],
      guidelineVersionLabel: "Public site — Debt Service Coverage Ratio (DSCR) Loan Program",
      effectiveDate: TODAY,
      lastVerifiedDate: TODAY,
      sourceCitation: "https://ardri.com/debt-service-coverage-ratio/",
      notes:
        "Public page states \"LTV up to 80% for Purchase and Rate/Term Refinance\", \"LTV up to 75% for Cash-out Refinance\", \"Minimum 600 FICO\", \"Jumbo Loan amounts up to $4M\", \"DSCR Down to .75 (No Ratio Loans Also Available)\", Non-Owner Occupied Only, First Time Investors allowed, 30YR I/O terms available, eligible for LLCs/Corporations/Trusts/Foreign Nationals/ITIN/Non-Permanent Resident Aliens, no reserve requirement, no prepayment penalty options. Minimum loan amount is not published on this page — $100,000 used here as a reasonable floor pending direct confirmation.",
    },
  },
];
