import { createClient } from "@supabase/supabase-js";
import fs from "fs";

const DRY_RUN = process.argv.includes("--dry-run");
const fileEnv = fs.existsSync(".env.local") ? Object.fromEntries(fs.readFileSync(".env.local", "utf8").split(/\r?\n/).filter((l) => l.includes("=")).map((l) => { const i=l.indexOf("="); return [l.slice(0,i), l.slice(i+1).trim().replace(/^(["'])(.*)\1$/, "$2")]; })) : {};
const env = { ...process.env, ...fileEnv };
if (!DRY_RUN && (!env.NEXT_PUBLIC_SUPABASE_URL || !env.SUPABASE_SERVICE_ROLE_KEY)) throw new Error("Missing Supabase credentials. Use --dry-run for payload validation.");
const admin = DRY_RUN ? null : createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);
const ORG = "bfe87b1c-86e7-4186-b1c4-ecc25d0e4420";
const REVIEWED = "2026-08-06";
const ADMIN = "nonqmnexusadmin@gmail.com";
const GENERAL = "https://d2ol7oe51mr4n9.cloudfront.net/user_3Cfrs4UEzyBfibhWL8hkQ0WuLXI/8940e0f4-fd1f-49cc-bc45-3b5018625ea0.pdf";
const CES = "https://d2ol7oe51mr4n9.cloudfront.net/user_3Cfrs4UEzyBfibhWL8hkQ0WuLXI/a4d49806-acf6-49dc-b8fa-9b799529b094.pdf";
const PRODUCTS = "https://bffws.com/products_new/";
const purposes = ["purchase","rate_term_refinance","cash_out_refinance"];
const homes = ["single_family","pud","townhome","condo","2_4_unit"];
const citizens = ["us_citizen","permanent_resident","non_permanent_resident"];
const common = (id, p) => ({ active:true,isSampleData:false,lenderId:id,eligibleStates:"ALL",lastVerifiedDate:REVIEWED,interestOnlyAvailable:false,prepaymentPenaltyOptions:["none"],minReservesMonths:0,...p });
const matrixNote = "The official narrative guideline confirms this program but defers scenario-specific LTV/FICO/loan-amount/reserve tiers to the current BFF matrix. Headline ceilings are retained only as searchable product ceilings; obtain the current matrix before final eligibility.";

function programs(id) { return [
  ["Full Doc Non-QM", common(id,{incomeDocTypes:["full_doc"],loanPurposes:purposes,occupancies:["primary","second_home","investment"],propertyTypes:homes,citizenshipEligible:citizens,vestingEligible:["individual","joint_tenants","trust","llc","corporation","partnership"],minLoanAmount:150000,maxLoanAmount:4000000,minFico:620,maxDti:55,baseMaxLtv:90,minSelfEmploymentMonths:24,matrixConfirmationRequired:true,matrixConfirmationNotes:matrixNote,sourceDocuments:[GENERAL],sourceCitation:`${GENERAL} pp.18,24-39,39-47,50-70,71-81; ${PRODUCTS}`,notes:"Published 02/23/2026. One- or two-year W-2/tax-return options; self-employed borrower generally requires 2 years. NPRE: 2 years U.S. residence and employment, valid SSN and EAD/eligible visa; 80% max Full/Expanded. Current matrix controls exact tiers."}),"BFF Loan Eligibility Guidelines — Published 02/23/2026","2026-02-23",GENERAL],
  ["Bank Statement", common(id,{incomeDocTypes:["bank_statement"],loanPurposes:purposes,occupancies:["primary","second_home","investment"],propertyTypes:homes,citizenshipEligible:citizens,vestingEligible:["individual","joint_tenants","trust"],minLoanAmount:75000,maxLoanAmount:4000000,minFico:620,baseMaxLtv:90,minSelfEmploymentMonths:24,bankStatementFlexible:true,matrixConfirmationRequired:true,matrixConfirmationNotes:matrixNote,sourceDocuments:[GENERAL],sourceCitation:`${GENERAL} pp.81-88; ${PRODUCTS}`,notes:"12 or 24 months personal/business statements. Personal: transfers from business, normally no expense factor when separate business account supported. Business/co-mingled: standard 50% expense factor; third-party expense factor minimum 10%; deposits/P&L variance no more than 20%. NSF tolerances are documented in §8.6.3. Tax returns/4506-C not required."}),"BFF Loan Eligibility Guidelines — Published 02/23/2026","2026-02-23",GENERAL],
  ["P&L Statement", common(id,{incomeDocTypes:["pnl_only"],loanPurposes:purposes,occupancies:["primary","second_home","investment"],propertyTypes:homes,citizenshipEligible:citizens,vestingEligible:["individual","joint_tenants","trust"],minLoanAmount:75000,maxLoanAmount:2500000,minFico:660,baseMaxLtv:80,minSelfEmploymentMonths:24,pnlPeriodMonths:12,pnlTaxReturnsRequired:false,pnlPreparerAttestationPurpose:"confirms_tax_filing_only",pnlSupportingBankStatementsMonths:2,matrixConfirmationRequired:true,matrixConfirmationNotes:"REQUIRES HUMAN REVIEW: §8.8 describes CPA/EA/CTEC/PTIN preparers, a PTIN tier capped at 75% primary/70% second-home-investment, and restrictions for an >80%-85% tier, while BFF's product page advertises an 80% headline. The current matrix is required to resolve exact preparer/occupancy/LTV tiers.",sourceDocuments:[GENERAL],sourceCitation:`${GENERAL} pp.88-89; ${PRODUCTS}`,notes:"P&L itself is the income document; tax returns and 4506-C are not required. 12 or 24 months permitted, minimum 25% ownership and 2 years self-employment/business existence. Preparer confirms preparation/filing of most recent business tax return; that attestation does not convert this into tax-return documentation."}),"BFF P&L Only — Published 02/23/2026","2026-02-23",GENERAL],
  ["1099 Only", common(id,{incomeDocTypes:["1099"],loanPurposes:purposes,occupancies:["primary","second_home","investment"],propertyTypes:homes,citizenshipEligible:citizens,vestingEligible:["individual","joint_tenants","trust"],minLoanAmount:75000,maxLoanAmount:4000000,minFico:620,baseMaxLtv:90,minSelfEmploymentMonths:24,matrixConfirmationRequired:true,matrixConfirmationNotes:matrixNote,sourceDocuments:[GENERAL],sourceCitation:`${GENERAL} p.89 §8.9`,notes:"One or two years 1099/1099 transcripts; 90% net margin or third-party P&L; 2-year history; YTD support when reporting period is >90 days; 4506-C required. Expanded Doc matrix controls exact tiers."}),"BFF 1099 Only — Published 02/23/2026","2026-02-23",GENERAL],
  ["WVOE Only", common(id,{incomeDocTypes:["wvoe_only"],loanPurposes:purposes,occupancies:["primary"],propertyTypes:["single_family","pud","townhome","condo","2_4_unit"],citizenshipEligible:citizens,vestingEligible:["individual","joint_tenants","trust"],minLoanAmount:75000,maxLoanAmount:1500000,minFico:680,baseMaxLtv:80,firstTimeHomebuyerAllowed:true,sourceDocuments:[GENERAL],sourceCitation:`${GENERAL} pp.89-90 §8.10`,eligibilityLtvMatrix:[{minFico:680,maxLoanAmount:1500000,loanPurpose:"purchase",occupancy:"primary",maxLtv:80},{minFico:680,maxLoanAmount:1500000,loanPurpose:"rate_term_refinance",occupancy:"primary",maxLtv:80},{minFico:680,maxLoanAmount:1500000,loanPurpose:"cash_out_refinance",occupancy:"primary",maxLtv:70}],notes:"Two years same employer, Form 1005, two personal bank statements supporting at least 65% of WVOE gross wages. Primary only. FTHB max 70%, no gifts. No paystubs, tax returns, W-2s or 4506-C."}),"BFF WVOE — Published 02/23/2026","2026-02-23",GENERAL],
  ["Asset Utilization", common(id,{incomeDocTypes:["asset_depletion"],loanPurposes:purposes,occupancies:["primary","second_home","investment"],propertyTypes:homes,citizenshipEligible:citizens,vestingEligible:["individual","joint_tenants","trust"],minLoanAmount:75000,maxLoanAmount:2500000,minFico:680,maxDti:45,baseMaxLtv:80,eligibilityLtvMatrix:[{minFico:680,maxLoanAmount:1500000,loanPurpose:"purchase",maxLtv:80},{minFico:680,maxLoanAmount:1500000,loanPurpose:"rate_term_refinance",maxLtv:80},{minFico:680,maxLoanAmount:1500000,loanPurpose:"cash_out_refinance",maxLtv:70},{minFico:680,maxLoanAmount:2500000,loanPurpose:"purchase",maxLtv:70},{minFico:680,maxLoanAmount:2500000,loanPurpose:"rate_term_refinance",maxLtv:70},{minFico:680,maxLoanAmount:2500000,loanPurpose:"cash_out_refinance",maxLtv:65}],sourceDocuments:[GENERAL],sourceCitation:`${GENERAL} pp.90-92 §8.11`,notes:"Sole or supplemental income; assets / 60. Three months/quarterly/VOD and 120-day seasoning. 100% checking/savings/money market and cash-value life insurance; 80% securities; retirement 70% at 59.5+, 60% under 59.5. Business assets, real-estate equity, restricted stock, cash-out proceeds and crypto are ineligible for depletion."}),"BFF Asset Utilization — Published 02/23/2026","2026-02-23",GENERAL],
  ["DSCR (1-4 Unit)", common(id,{incomeDocTypes:["dscr"],loanPurposes:purposes,occupancies:["investment"],propertyTypes:[...homes,"non_warrantable_condo","condotel"],citizenshipEligible:[...citizens,"foreign_national"],vestingEligible:["individual","llc","corporation","partnership"],minLoanAmount:75000,maxLoanAmount:3500000,minFico:640,minDscr:0,baseMaxLtv:85,firstTimeInvestorAllowed:true,foreignNationalDscrEligible:true,strIncomeEligible:true,strIncomeMaxLtv:75,strIncomeNotes:"Purchase max 75%; refinance max 70%; 12-month seasonality and minimum 20% expense factor. AirDNA purchase allowed subject to report/comparable/score requirements.",giftFundsAllowed:true,giftFundsNotes:"Permitted after 10% borrower contribution; not reserves.",matrixConfirmationRequired:true,matrixConfirmationNotes:matrixNote,sourceDocuments:[GENERAL],sourceCitation:`${GENERAL} pp.92-99 §§8.12-8.13; ${PRODUCTS}`,notes:"Business-purpose investment. Product page confirms no-ratio option; current matrix controls no-ratio leverage. First-time investor: 680, DSCR >=1, max 80% and motivation letter. First-time owner+investor: 700, $150K-$1.5M, 1-unit/warrantable condo, 12 months reserves, no cash-out/STR/IO/40-year/gifts. NPRE max 75%. Foreign National is a distinct DSCR subset; no U.S. FICO may use foreign/alternative credit treated as 680."}),"BFF Loan Eligibility Guidelines — Published 02/23/2026","2026-02-23",GENERAL],
  ["DSCR (5-8 Unit / Mixed Use)", common(id,{incomeDocTypes:["dscr"],loanPurposes:purposes,occupancies:["investment"],propertyTypes:["5_8_unit"],citizenshipEligible:citizens,vestingEligible:["individual","llc","corporation","partnership"],minLoanAmount:150000,maxLoanAmount:2000000,minFico:700,minDscr:1,baseMaxLtv:75,experiencedInvestorRequired:true,firstTimeInvestorAllowed:false,fiveToEightUnitMinDscr:1,fiveToEightUnitExperiencedInvestorRequired:true,fiveToEightUnitCitizenshipEligible:citizens,fiveToEightUnitStrIncomeEligible:false,giftFundsAllowed:false,prepaymentPenaltyOptions:["fixed percentage only"],matrixConfirmationRequired:true,matrixConfirmationNotes:matrixNote,sourceDocuments:[GENERAL],sourceCitation:`${GENERAL} pp.99-102 §8.14; ${PRODUCTS}`,notes:"5-8 residential or 2-8 mixed use; experienced investors only. Vacant residential limits; no vacant commercial space. Commercial space/income <=49.99%, retail/office/restaurant only. Max 2 acres; no STR income; no gifts; 30-year maximum term."}),"BFF DSCR 5-8 / Mixed Use — Published 02/23/2026","2026-02-23",GENERAL],
  ["Cross Collateral DSCR", common(id,{incomeDocTypes:["dscr"],loanPurposes:purposes,occupancies:["investment"],propertyTypes:["single_family","pud","townhome","condo","2_4_unit"],citizenshipEligible:citizens,vestingEligible:["individual","llc","corporation","partnership"],minLoanAmount:150000,maxLoanAmount:6250000,minFico:700,minDscr:1,baseMaxLtv:80,experiencedInvestorRequired:true,firstTimeInvestorAllowed:false,strIncomeEligible:true,strIncomeMaxLtv:60,strIncomeNotes:"Official product page: STR eligible at 60% LTV with 1.25 DSCR.",cashOutLimits:[{maxLtv:100,maxCashOutAmount:1000000}],matrixConfirmationRequired:true,matrixConfirmationNotes:"The guide refers cross-collateral eligibility to its separate matrix. Product-page figures (2-25 properties, $6.25M, 80%, 700 FICO, $1M cash-out) are searchable ceilings pending current matrix confirmation.",sourceDocuments:[GENERAL],sourceCitation:`${GENERAL} p.102 §9; ${PRODUCTS}`,notes:"Blanket DSCR product. Official page states 2-25 investment properties, combined-rent-roll DSCR, up to $6.25M and $1M cash-out. Foreign Nationals are explicitly ineligible in the 02/23/2026 guide."}),"BFF Cross Collateral — Published 02/23/2026","2026-02-23",GENERAL],
  ["ITIN", common(id,{incomeDocTypes:["full_doc","bank_statement","1099"],loanPurposes:purposes,occupancies:["primary","second_home"],propertyTypes:["single_family","pud","townhome","condo","2_4_unit"],citizenshipEligible:["itin"],vestingEligible:["individual"],minLoanAmount:150000,maxLoanAmount:1500000,minFico:680,maxDti:50,baseMaxLtv:80,itinSpecialist:true,ownerOccupiedItinEligible:true,investmentItinEligible:false,noFicoPolicy:"requires_us_fico",matrixConfirmationRequired:true,matrixConfirmationNotes:"The 02/23/2026 guide defers ITIN numeric tiers to the separate ITIN matrix; existing verified program-page ceilings are preserved.",sourceDocuments:[GENERAL],sourceCitation:`${GENERAL} pp.26-27 §4.1.4; ${PRODUCTS}`,notes:"Valid ITIN and at least 2 years consistent ITIN payments; ITIN letter required. DACA eligible with valid U.S. driver's license and EAD. Owner-occupied select ITIN products only; investment not confirmed. No-FICO ITIN is not established by these sources."}),"BFF ITIN — Published 02/23/2026","2026-02-23",GENERAL],
  ["Foreign National", common(id,{incomeDocTypes:["dscr"],loanPurposes:purposes,occupancies:["investment"],propertyTypes:["single_family","pud","townhome","condo","non_warrantable_condo","condotel","2_4_unit"],citizenshipEligible:["foreign_national"],vestingEligible:["individual","llc","corporation","partnership"],minLoanAmount:150000,maxLoanAmount:1500000,minFico:0,minDscr:1,baseMaxLtv:75,noFicoPolicy:"eligible_with_alternative_credit",noFicoMaxLtv:75,foreignNationalDscrEligible:true,foreignNationalSpecialist:true,minReservesMonths:6,matrixConfirmationRequired:true,matrixConfirmationNotes:matrixNote,sourceDocuments:[GENERAL],sourceCitation:`${GENERAL} pp.27-31 §§4.1.5-4.1.14; ${PRODUCTS}`,notes:"Investment DSCR only; no primary/second home, Full Doc or Expanded Doc. No-FICO may qualify using foreign/alternative credit; alternative credit treated as 680. U.S.-credit borrowers minimum 680. Passport/legal-entry, foreign residence, ACH from U.S. bank, OFAC screening required. No gifts. Ineligible for 5-8/mixed use/cross collateral."}),"BFF Foreign National — Published 02/23/2026","2026-02-23",GENERAL],
  ["DSCR Closed-End Second — Premier", common(id,{incomeDocTypes:["dscr"],loanPurposes:["second_lien"],occupancies:["investment"],propertyTypes:["single_family","pud","townhome","condo","2_4_unit"],citizenshipEligible:["us_citizen","permanent_resident"],vestingEligible:["individual","trust","llc","corporation","partnership"],minLoanAmount:50000,maxLoanAmount:850000,minFico:660,minDscr:1,baseMaxLtv:90,lienPosition:"standalone_second",ltvMetric:"cltv",experiencedInvestorRequired:true,firstTimeInvestorAllowed:false,firstTimeHomebuyerAllowed:false,strIncomeEligible:true,giftFundsAllowed:false,premierProduct:true,prepaymentPenaltyOptions:["minimum 1 year where legal"],matrixConfirmationRequired:true,matrixConfirmationNotes:"The 10/01/2025 CES guideline confirms minimum DSCR 1.00 and product rules but defers DSCR CES FICO/CLTV/loan-amount/reserve tiers to the current CES matrix. $850K/90%/660 are official overall CES product ceilings, not represented as flat DSCR-second availability.",sourceDocuments:[CES],sourceCitation:`${CES} pp.6-31, especially §§2.1-2.20, 3.1-3.10, 4.1, 5.3-5.4, 6.5-6.9, 8.9; ${PRODUCTS}`,notes:"PREMIER BFF PRODUCT. Investment/business-purpose, standalone cash-out only; no purchase/piggyback, primary, second home, Foreign National, no-SSN or first-time investor. Minimum DSCR 1.00; 12 months investor experience in past 36. 6 months ownership/refi seasoning. 12-month primary and subject housing history; 48-month major-credit-event seasoning. SFR/PUD/townhome/modular, warrantable condo and 2-4 units; no rural, condotel, non-warrantable condo, mixed-use, manufactured, log, co-op or unique. Current first-lien note/statement required; senior lien restrictions apply. No max note rate specified."}),"BFF Home Equity Closed-End Seconds — Effective 10/01/2025","2025-10-01",CES],
]; }

async function adminId(){const {data,error}=await admin.from("users").select("id").eq("email",ADMIN).single();if(error)throw error;return data.id;}
async function lender(createdBy){const {data,error}=await admin.from("lenders").select("id,name,notes").eq("organization_id",ORG).ilike("name","%First Funding%");if(error)throw error;let row=data?.find((x)=>/brokers? first funding/i.test(x.name));if(!row){const q=await admin.from("lenders").insert({organization_id:ORG,name:"Brokers First Funding",tier_level:3,active:true,is_sample_data:false,created_by:createdBy,notes:"BFF Wholesale / FlexPoint Inc. Full Non-QM shelf plus premier DSCR Closed-End Second."}).select("id,name").single();if(q.error)throw q.error;row=q.data;}else{await admin.from("lenders").update({active:true,notes:`${row.notes??""} Audited ${REVIEWED}: official 02/23/2026 general guide and 10/01/2025 CES guide; DSCR Closed-End Second designated premier product.`}).eq("id",row.id);}return row.id;}
async function upsert(lenderId,def,createdBy){const [name,config,label,effectiveDate,sourceUrl]=def;const {data:found,error}=await admin.from("programs").select("id,config").eq("lender_id",lenderId).eq("name",name).limit(1);if(error)throw error;let id;if(found?.[0]){id=found[0].id;const merged={...found[0].config,...config,guidelineVersionLabel:label,effectiveDate};const q=await admin.from("programs").update({config:merged,active:true,updated_at:new Date().toISOString()}).eq("id",id);if(q.error)throw q.error;console.log(`Updated: ${name}`);}else{const q=await admin.from("programs").insert({organization_id:ORG,lender_id:lenderId,name,is_sample_data:false,active:true,config:{...config,guidelineVersionLabel:label,effectiveDate},created_by:createdBy}).select("id").single();if(q.error)throw q.error;id=q.data.id;console.log(`Created: ${name}`);}const {data:gv}=await admin.from("guideline_versions").select("id").eq("program_id",id).eq("label",label).limit(1);if(!gv?.length){const q=await admin.from("guideline_versions").insert({organization_id:ORG,program_id:id,label,effective_date:effectiveDate,last_verified_date:REVIEWED,verification_status:"human_verified",reviewed_by:createdBy,published_at:new Date().toISOString(),source_url:sourceUrl});if(q.error)throw q.error;}return id;}
async function main(){if(DRY_RUN){const p=programs("dry-run");console.log(JSON.stringify({lender:"Brokers First Funding",programCount:p.length,programs:p.map(([name,c,label,effectiveDate])=>({name,label,effectiveDate,minFico:c.minFico,maxLoanAmount:c.maxLoanAmount,baseMaxLtv:c.baseMaxLtv,incomeDocTypes:c.incomeDocTypes,loanPurposes:c.loanPurposes,premierProduct:c.premierProduct??false,matrixConfirmationRequired:c.matrixConfirmationRequired??false}))},null,2));return;}const createdBy=await adminId();const lenderId=await lender(createdBy);const defs=programs(lenderId);for(const d of defs)await upsert(lenderId,d,createdBy);const names=defs.map(([n])=>n);const {data,error}=await admin.from("programs").select("name,active,config").eq("lender_id",lenderId).in("name",names);if(error)throw error;const map=new Map((data??[]).map((r)=>[r.name,r]));const check=(v,m)=>{if(!v)throw new Error(`BFF production validation failed: ${m}`)};check(map.size===defs.length,`expected ${defs.length}, found ${map.size}`);for(const name of names)check(map.get(name)?.active&&map.get(name)?.config?.active,`${name} inactive`);const ces=map.get("DSCR Closed-End Second — Premier")?.config;check(ces?.premierProduct===true&&ces?.lienPosition==="standalone_second"&&ces?.ltvMetric==="cltv"&&ces?.minDscr===1,"DSCR CES premier fields");check(ces?.loanPurposes?.length===1&&ces.loanPurposes[0]==="second_lien"&&ces?.occupancies?.length===1&&ces.occupancies[0]==="investment","DSCR CES purpose/occupancy");const w=map.get("WVOE Only")?.config;check(w?.minFico===680&&w?.maxLoanAmount===1500000&&w?.eligibilityLtvMatrix?.length===3,"WVOE exact tiers");const a=map.get("Asset Utilization")?.config;check(a?.maxDti===45&&a?.eligibilityLtvMatrix?.length===6,"asset-utilization tiers");console.log(`BFF production validation passed: ${map.size} active programs; premier DSCR CES and exact WVOE/Asset Utilization fields verified.`);}
main().catch((e)=>{console.error(e);process.exit(1);});
